n_iters: 2000
n_suggestions: 1

features_path: "data/zinc_dft/feature_list_mfp2048_rdd.npz"
values_path: "data/zinc_dft/properties.csv"
initial_n_obs: 10

predictor_class: LightGBMPredictor
predictor_args:
  n_estimators: 100
  seed: 0
  use_uncertainty: true
  quantiles: [0.1, 0.9]

selector_class: SteinNoveltySelector
selector_args:
  sigma: 1
  normalize_features: false
  value_normalization: default
  chunk_size: 512
  use_uncertainty: true
  uncertainty_ratio: 0.5
  uncertainty_aggregation_type: mean
  # print_uncertainty: true
  pred_clip:
    - [0, null]
    - [0, null]

report_interval: 10
scatter_plot_intervals: [2, 5, 20, 50, 200, 500, 2000, 5000, 20000, 50000]
verbose_plot: false
output_dir: "results"