n_iters: 2000
sigma: 1
n_suggestions: 1

features_path: "data/zinc_dft/feature_list_mfp2048_rdd.npz"
values_path: "data/zinc_dft/properties.csv"
initial_n_obs: 10

predictor_class: LightGBMPredictor
predictor_args:
  n_estimators: 100
  seed: 0

selector_class: BLOX2Selector
selector_args:
  normalize_features: false
  value_normalization: default
  n_chunks: 512
  use_distribution: false
  # pooling: "mean"
  pred_clip:
    - [0, null]
    - [0, null]

report_interval: 50
scatter_plot_intervals: [2, 5, 20, 50, 200, 500, 2000, 5000, 20000, 50000]
verbose_plot: false
output_dir: "results"