n_iters: 100
sigma: 1
n_suggestions: 1

features_path: "data/zinc_dft/feature_list_mfp2048_rdd.npz"
values_path: "data/zinc_dft/properties.csv"
initial_n_obs: 10

predictor_class: RandomForestPredictor
predictor_args:
  n_estimators: 10
  random_state: 0

selector_class: BLOX2Selector
selector_args:
  normalize_features: false
  value_normalization: before_pred
  n_chunks: 512
  use_distribution: true
  pooling: "max"

report_interval: 1
scatter_plot_intervals: [2, 5, 20, 50, 200, 500, 2000, 5000, 20000, 50000]
verbose_plot: true
output_dir: "results"