n_iters: 2000
squared_sigma: 1
n_suggestions: 1

features_path: "data/zinc_dft/feature_list_mfp2048.csv"
values_path: "data/zinc_dft/properties.csv"
initial_n_obs: 10

predictor_class: RandomForestPredictor
predictor_args:
  n_estimators: 100
  random_state: 0

selector_class: RandomSelector

report_interval: 50
scatter_plot_intervals: [200, 500, 2000, 5000, 20000, 50000]
output_dir: "results"
